# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a5436b4b95edb348fb3690669ad4008394ff364af0fef2b7e87a7d09672bbda34de44769df0f00a8e7c1e957b0cc407cb5fc5e0f7329752c892fd65990ec647

test:
  secret_key_base: bfaf0ae88915370c58898ebdc664d86a03fb83aa7fb610b6617d8d423bdc4a60502dba347d2e8d0656e7d46de6f1b31e2c77dbbe05a71bc30afe44c2c9414f0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
